apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-commenter-leader-election-rolebinding
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-commenter-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: argocd